name: main
on: 
  push:
    branches: master

jobs:
  docker-buld-push:
    strategy:
      matrix:
        repo: [ 'frontend', 'backend' ]
    uses: ./.github/workflows/reusable-docker.yml
    with:
      image-name: devboard-${{ matrix.repo }}
      tag: latest
      docker-name: rohit5126
      context: ${{ matrix.repo }}
    secrets: 
      docker_username: ${{ vars.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_TOKEN }}
    
    
  deploy:
     needs: [docker-buld-push]
     runs-on: self-hosted
     steps:
       - name: code
         uses: actions/checkout@v6
       - name: docker deploy
         run: |
           cp .env.example .env
           docker compose up
 
  
    
